steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/shopify-pos-display/shopify-pos-backend:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/shopify-pos-display/shopify-pos-backend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/shopify-pos-deployment', 'shopify-pos=gcr.io/shopify-pos-display/shopify-pos-backend:$COMMIT_SHA']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=shopify-pos-cluster'

images:
  - 'gcr.io/shopify-pos-display/shopify-pos-backend:$COMMIT_SHA'
