steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/shopify-pos-display/shopify-pos-backend:latest', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/shopify-pos-display/shopify-pos-backend:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=shopify-pos-cluster'
    args: ['apply', '-f', 'deployment.yml']
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=shopify-pos-cluster'
    args: ['apply', '-f', 'service.yaml']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/shopify-pos-display/shopify-pos-backend:latest'
